name: Iva
markdown: redcarpet
pygments: true

title: Engineering Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://n7down.github.io"
email: Joshua.sovanh.adams@gmail.com
github: n7down
linkedin: https://www.linkedin.com/in/joshua-josh-adams-5573bb18
